### ISSUE TITLE
Not Python 2 friendly

### ISSUE THREAD

**Issue by thatiane** [jooaodanieel/GCommit#16]
When I try to execute using Python version 2.7, shows this error:
`Traceback (most recent call last):
  File "/usr/local/bin/git-gcommit", line 100, in <module>
    main()
  File "/usr/local/bin/git-gcommit", line 95, in main
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined`

**Comment by hegde5** [comment]
I will take this one.

**Comment by jooaodanieel** [comment]
@thatiane did you see? This issue was quickly closed!
Now it might work for you :rocket:
