### ISSUE TITLE
Turn GCommit into a commit wrapper

### ISSUE THREAD

**Issue by jooaodanieel** [jooaodanieel/GCommit#2]
`git gcommit` is not a `git commit` wrapper, but it would be nice to have it as a full wrapper that only adds the team-signature behavior.

Suggestion: use a new flag that accept a list to differentiate from default `git commit` behavior, for example, add a `git commit --team [ID1 ...]`

**Comment by jakes44** [comment]
Any good resources on this? All I can find is info on making an entirely new subcommand, rather than extending an existing one...

**Comment by LucianaMarques** [comment]
Do you mean making a [commit](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) squash?

**Comment by jooaodanieel** [comment]
Hey @LucianaMarques 
No, what I'm trying to say is to turn GCommit into a replacer for `git commit`, with a extension for multiple devs signatures, so that you can run, say, `git gcommit --amend` and it calls `git commit --amend`.

**Comment by eamanu** [comment]
Hello, 

I am thinking about this issue. 

First I think that we have to create a method/class named Commit (already exist), so, this have to receive the sys.argv[1:]. Then, this have to verify if the args receive for gcommit correspond to a commit (maybe using regex or some python-git module). 

Then if this fail, use gcommit normally. I don't know if exist another idea.

**Comment by jooaodanieel** [comment]
I think that's a great way @eamanu, that was kinda the path I thought
