### ISSUE TITLE
Make the contributors table as a 5 x n grid

### ISSUE THREAD

**Issue by jooaodanieel** [jooaodanieel/GCommit#43]
It would be great to improve the space used by the contributors table by spreading it across each line.
My guess is that making a 5 column-wide is enough.

> note: not sure if markdown will be the right tool, but always remember that HTML is also accepted

**Comment by iamjoross** [comment]
Hello @jooaodanieel , Im interested in working on it! Do you mind if I work on this?

**Comment by jooaodanieel** [comment]
Sure, @iamjoross !

**Comment by jooaodanieel** [comment]
And don't forget to add yourself to the list :) @iamjoross
