### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jooaodanieel** [jooaodanieel/GCommit#44]
The project could really use a set of automated tests.
This issue requests the installation of a tool for writting tests and some test code

**Comment by vijiboy** [comment]
I would like to propose tests, using python unittest.

**Comment by jooaodanieel** [comment]
Great! Issue's yours, @vijiboy

**Comment by vijiboy** [comment]
@jooaodanieel 
apology for late reply. Wanted to know if I can still work on this task or Is this project stalled ? 
let me know, thanks.

**Comment by jooaodanieel** [comment]
> @jooaodanieel
> apology for late reply. Wanted to know if I can still work on this task or Is this project stalled ?
> let me know, thanks.

Be my guest, send a PR :)

**Comment by vijiboy** [comment]
ah cool. thanks.
