### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by jooaodanieel** [jooaodanieel/GCommit#5]
The code is poorly documented and this could be enhanced.

**Comment by ethchest** [comment]
I could add some comments... but the code is quite short so maybe it isn't that bad. Would you like a comment for every function?

**Comment by jooaodanieel** [comment]
I agree that the code is very short, I'm not used to Python's documentation standards
I guess it won't be necessary indeed. Thanks for the heads-up @ethchest !

**Comment by ethchest** [comment]
I think you can make your own documentation standards. Not sure if there are 'official' ones. But generally, the shorter the code, the less need for comments I would say.
